# Generated by Django 3.0.7 on 2020-07-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
