# Generated by Django 3.0.7 on 2020-07-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200711_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='codertjay', max_length=30),
            preserve_default=False,
        ),
    ]
