# Generated by Django 3.0.7 on 2020-07-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200712_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='appartment_address',
            new_name='apartment_address',
        ),
    ]
