# Generated by Django 3.0.7 on 2020-07-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_accessory',
            field=models.CharField(blank=True, choices=[('cl', 'Cloth'), ('ba', 'Bag'), ('Fu', 'Furniture'), ('Bo', 'Book'), ('La', 'Laptop'), ('Ph', 'Phone'), ('Ca', 'Camera'), ('Ch', 'Charger'), ('He', 'Headset'), ('Mo', 'Mouse')], max_length=5, null=True),
        ),
    ]
